# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
description: Gardener shoot extension deploying the SOC runtime-security stack.
name: gardener-extension-shoot-rtsecurity-service
version: 0.2.0
