# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: shoot-rtsecurity-service
build:
  insecureRegistries:
    - garden.local.gardener.cloud:5001
  tagPolicy:
    customTemplate:
      template: "{{.version}}-{{.sha}}"
      components:
        - name: version
          envTemplate:
            template: "{{.EXTENSION_VERSION}}"
        - name: sha
          gitCommit:
            variant: AbbrevCommitSha
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-rtsecurity-service
      ko:
        dependencies:
          paths:
            - charts
            - cmd/gardener-extension-shoot-rtsecurity-service
            - pkg
            - VERSION
        flags:
          - -mod=vendor
          - -trimpath
        ldflags:
          - "{{.LD_FLAGS}}"
        main: ./cmd/gardener-extension-shoot-rtsecurity-service/
    - image: local-skaffold/gardener-extension-shoot-rtsecurity-service/charts/extension
      custom:
        buildCommand: |
          bash ${EXTENSION_GARDENER_HACK_DIR}/push-helm.sh charts/gardener-extension-shoot-rtsecurity-service .image
        dependencies:
          paths:
            - charts/gardener-extension-shoot-rtsecurity-service
      requires:
        - image: local-skaffold/gardener-extension-shoot-rtsecurity-service
          alias: IMG
