apiVersion: v1
kind: Secret
metadata:
  name: gardener-extension-admission-shoot-falco-service-config
  namespace: {{ .Release.Namespace }}
stringData:
  config.yaml: |
    apiVersion: falco.extensions.config.gardener.cloud/v1alpha1
    kind: Configuration
    falco:
      {{- toYaml .Values.config | nindent 6 }}
