{{- if and .Values.credentials.directAlertsJwtKey .Values.credentials.directAlertsJwtPub }}
---
apiVersion: v1
kind: Secret
metadata:
  name: node-agent-direct-jwt
  namespace: {{ .Values.namespaces.honey }}
type: Opaque
data:
  key.pem: {{ .Values.credentials.directAlertsJwtKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: node-agent-direct-jwt-pub
  namespace: {{ .Values.namespaces.honey }}
type: Opaque
data:
  public.pem: {{ .Values.credentials.directAlertsJwtPub | b64enc }}
{{- end }}
