# restrict Falco extension usage to enabled namespaces only
restrictedUsage: false

# restrict Falco centralized logging to enabled namespaces only
# enable if NO centralized storage is deployed
restrictedCentralizedLogging: true

# make destination "otlp" only available in dev environments. Eventually, 
# this will be the default "logging" destination
otlpLogging: false

image:
  repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/admission-shoot-falco-service
  pullPolicy: IfNotPresent
replicaCount: 1
resources: {}
healthPort: 8081
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      memory: 64Mi
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
webhookConfig:
  serverPort: 10250
kubeconfig: ""

service:
  topologyAwareRouting:
    enabled: false

gardener:
  virtualCluster:
    enabled: true
    serviceAccount: {}
  runtimeCluster: {}
  autonomousShootCluster: false

# Extension config passed to admission controller (optional).
# config:
#   globalDefaultDestinations:
#   - name: "central-splunk"
#     falcosidekickOutput:
#       key: "splunk"
#       value:
#         host: "https://falco-splunk.<<.SeedIngressDomain>>"
#         token: "<<.ServiceAccountToken>>"
#         checkcert: true
